"use strict";

/**
 * services/loyaltyService.js
 *
 * CHANGES FROM ORIGINAL:
 *   - SHA-256 password hashing → argon2
 *   - All user input sanitized before Sheets writes
 *   - Structured error objects instead of throw strings
 *   - No user enumeration on login (same error for wrong user vs wrong password)
 *   - `getByToken` no longer exported — internal only
 *   - Rate-limit-friendly: login does not leak whether email exists
 *   - QR token is now generated by qrService (HMAC-signed, TTL-bound)
 *     The token stored in Sheets is the customer UID, NOT the signed QR
 *   - Full JSDoc for maintainability
 */

const { generateCustomerId, verifyQrToken }      = require("../qrService");

const { redisClient: redis }                     = require ("../../utils/redis");
const crypto = require("crypto");

/* ─────────────────────────────────────────────────────────────
   QR VALIDATION + REDEMPTION
───────────────────────────────────────────────────────────── */

/**
 * Validate a scanned QR token and record a redemption.
 *
 * Security guarantees:
 *   1. HMAC signature verified by qrService.verifyQrToken()
 *   2. Token TTL verified (short-lived — default 5 min)
 *   3. Replay: check token not already in Redemptions sheet
 *   4. Per-day deduplication: same customer+offer+partner = 1/day
 *   5. Offer must exist and be active
 *   6. Customer must be active
 *
 * @param {string} token       - Signed HMAC token from QR
 * @param {string} offerId     - Offer ID partner is applying
 * @param {string} partnerId   - Authenticated partner ID from session
 */

async function prevalidateQr({ token, partnerId } = {}) {
  if (!token || !partnerId) {
    return { success: false, message: "Dati mancanti." };
  }

  /* 1. VERIFY QR */
  const check = verifyQrToken(token);

  if (!check.valid) {
    const messages = {
      TOKEN_MISSING: "QR mancante.",
      TOKEN_MALFORMED: "QR non valido.",
      TOKEN_INVALID_SIGNATURE: "QR non autentico — rifiuta la transazione.",
      TOKEN_EXPIRED: "QR scaduto. Chiedi al cliente di aggiornare il QR.",
    };

    return {
      success: false,
      code: check.reason,
      message: messages[check.reason] || "QR non valido.",
      expiresAt: null,
    };
  }

  const { customerId, exp } = check;

  /* 2. PARALLEL LOAD (customer + offers) */
  const [customerRes, offers] = await Promise.all([
    db.query(
      `SELECT id, full_name, active FROM customers WHERE id = $1`,
      [customerId]
    ),
    getPartnerOffers(partnerId),
  ]);

  const customer = customerRes.rows[0];

  if (!customer) {
    return {
      success: false,
      code: "CUSTOMER_NOT_FOUND",
      message: "Cliente non trovato.",
      expiresAt: null,
    };
  }

  if (!customer.active) {
    return {
      success: false,
      code: "CUSTOMER_SUSPENDED",
      message: "Account cliente sospeso.",
      expiresAt: null,
    };
  }

  /* 3. BULK FETCH ALL REDEMPTIONS (IMPORTANT OPTIMIZATION) */
  const redemptionsRes = await db.query(
    `
    SELECT offer_id
    FROM redemptions
    WHERE customer_id = $1
      AND partner_id = $2
    `,
    [customerId, partnerId]
  );

  const usedOffers = new Set(redemptionsRes.rows.map(r => r.offer_id));

  /* 4. BUILD RESPONSE (O(N) ONLY) */
  const eligibleOffers = offers.map((offer) => {
    const used = usedOffers.has(offer.id);

    return {
      id: offer.id,
      title: offer.title,
      description: offer.description,
      eligible: !used,
      createdAt: offer.created_at,
      reason: used ? "Già utilizzata" : null,
    };
  });

  return {
    success: true,
    customerId,
    customerName: customer.full_name,
    expiresAt: exp,
    eligibleOffers,
  };
}

/* ─────────────────────────────────────────────────────────────
   REDEMPTION — FULL ATOMIC FLOW
   Layer 1: QR signature + expiry      (qrService.verifyQrToken)
   Layer 2: QR replay lock             (Redis SET NX)
   Layer 3: Permanent offer lock       (Redis SET NX, no TTL)
   Layer 4: Idempotency key            (Redis SET NX EX 300)
   Layer 5: Sheets audit write         (fire-and-forget)
───────────────────────────────────────────────────────────── */
async function redeemOffer({ token, offerId, partnerId } = {}) {
  /* 1. VERIFY QR */
  const check = verifyQrToken(token);

  if (!check.valid) {
    const messages = {
      TOKEN_MISSING: "QR mancante.",
      TOKEN_MALFORMED: "QR non valido.",
      TOKEN_INVALID_SIGNATURE: "QR non autentico.",
      TOKEN_EXPIRED: "QR scaduto. Chiedi al cliente di aggiornare il QR.",
    };

    return {
      success: false,
      code: check.reason,
      message: messages[check.reason] || "QR non valido.",
    };
  }

  const customerId = String(check.customerId).trim();

  /* 2. SHORT REDIS LOCK (ONLY FOR DOUBLE SCAN PROTECTION) */
  const tokenHash = crypto.createHash("sha256").update(token).digest("hex");
  const lockKey = `mm:scanlock:${tokenHash}:${offerId}`;

  const locked = await redis.set(lockKey, "1", {
    nx: true,
    ex: 5,
  });

  if (!locked) {
    return {
      success: false,
      code: "SCAN_TOO_FAST",
      message: "Scansione già in corso. Riprova.",
    };
  }

  try {
    /* 3. PARALLEL LOAD (customer + offer) */
    const [customerRes, offerRes] = await Promise.all([
      db.query(
        `SELECT id, full_name, active FROM customers WHERE id = $1`,
        [customerId]
      ),
      db.query(
        `SELECT id, title, active 
         FROM offers 
         WHERE id = $1 AND (partner_id = $2 OR partner_id = $3)`,
        [offerId, partnerId, "Globale"]
      ),
    ]);

    const customer = customerRes.rows[0];
    const offer = offerRes.rows[0];

    if (!customer) {
      return { success: false, code: "CUSTOMER_NOT_FOUND", message: "Cliente non trovato." };
    }

    if (!customer.active) {
      return { success: false, code: "CUSTOMER_SUSPENDED", message: "Account cliente sospeso." };
    }

    if (!offer || !offer.active) {
      return { success: false, code: "OFFER_INVALID", message: "Offerta non valida o non attiva." };
    }

    /* 4. INSERT (DB GUARANTEES UNIQUENESS) */
    const redemptionId =
      `r-${Date.now()}-${crypto.randomBytes(4).toString("hex")}`;

    try {
      await db.query(
        `
        INSERT INTO redemptions (
          id,
          customer_id,
          partner_id,
          offer_id,
          used_token,
          redeemed_at
        )
        VALUES ($1, $2, $3, $4, $5, NOW())
        `,
        [redemptionId, customerId, partnerId, offerId, token]
      );
    } catch (err) {
      if (err.code === "23505") {
        return {
          success: false,
          code: "OFFER_ALREADY_REDEEMED",
          message: "Questo cliente ha già utilizzato questa offerta.",
        };
      }
      throw err;
    }

    return {
      success: true,
      redemptionId,
      customerName: customer.full_name,
      offerTitle: offer.title,
      redeemedAt: new Date().toISOString(),
    };

  } finally {
    await redis.del(lockKey).catch(() => {});
  }
}

/* ─────────────────────────────────────────────────────────────
   EXPORTS
───────────────────────────────────────────────────────────── */

module.exports = {
  prevalidateQr,
  redeemOffer,
};
