"use strict";

/**
 * services/loyaltyService.js
 *
 * CHANGES FROM ORIGINAL:
 *   - SHA-256 password hashing → bcrypt (cost 12)
 *   - All user input sanitized before Sheets writes
 *   - Structured error objects instead of throw strings
 *   - No user enumeration on login (same error for wrong user vs wrong password)
 *   - `getByToken` no longer exported — internal only
 *   - Rate-limit-friendly: login does not leak whether email exists
 *   - QR token is now generated by qrService (HMAC-signed, TTL-bound)
 *     The token stored in Sheets is the customer UID, NOT the signed QR
 *   - Full JSDoc for maintainability
 */

const bcrypt = require("bcrypt");
const { appendRow, getSheetValues } = require("./sheetsService");
const { clean } = require("../utils/sanitizer");
const { generateCustomerId } = require("./qrService");
const { hashPassword, verifyPassword } = require("../utils/argon2");

const SHEET = {
  CUSTOMERS:   "Customers",
  REDEMPTIONS: "Redemptions",
  OFFERS:      "Offers",
};

const BCRYPT_ROUNDS = 12;

/* ─────────────────────────────────────────────────────────────
   SHEET READERS
   Each function reads + maps one sheet tab.
   Reminder: header row is always row[0] — strip it.
───────────────────────────────────────────────────────────── */

async function readCustomers() {
  const rows = await getSheetValues(SHEET.CUSTOMERS);
  return rows.slice(1).map((r) => ({
    id:             r[0],
    full_name:      r[1],
    identifier:     r[2],
    identifierType: r[3],
    passwordHash:   r[4],
    active:         r[5] === "true" || r[5] === "TRUE",
    createdAt:      r[6],
  }));
}

async function readRedemptions() {
  const rows = await getSheetValues(SHEET.REDEMPTIONS);
  return rows.slice(1).map((r) => ({
    id:          r[0],
    customerId:  r[1],
    partnerId:   r[2],
    offerId:     r[3],
    usedToken:   r[4],  // the HMAC token that was consumed (replay guard)
    date:        r[5],
    createdAt:   r[6],
  }));
}

async function readOffers() {
  const rows = await getSheetValues(SHEET.OFFERS);
  return rows.slice(1).map((r) => ({
    id:          r[0],
    title:       r[1],
    description: r[2],
    partnerId:   r[3],
    active:      r[4] === "true" || r[4] === "TRUE",
    createdAt:   r[5],
  }));
}

/* ─────────────────────────────────────────────────────────────
   HELPERS
───────────────────────────────────────────────────────────── */

function normalizeIdentifier(identifier) {
  const trimmed = identifier.trim().toLowerCase();
  return trimmed.includes("@")
    ? trimmed
    : trimmed.replace(/[^\d+]/g, "");
}

function detectIdentifierType(identifier) {
  return identifier.includes("@") ? "email" : "phone";
}

/* ─────────────────────────────────────────────────────────────
   REGISTER
───────────────────────────────────────────────────────────── */

/**
 * Register a new customer.
 * Returns { success: true, customerId } or throws with a safe message.
 */
async function register({ full_name, identifier, password }) {
  if (!full_name?.trim() || !identifier?.trim() || !password) {
    const e = new Error("Tutti i campi sono obbligatori.");
    e.statusCode = 400;
    throw e;
  }

  if (password.length < 8) {
    const e = new Error("La password deve avere almeno 8 caratteri.");
    e.statusCode = 400;
    throw e;
  }

  const normalized = normalizeIdentifier(identifier);
  const customers  = await readCustomers();

  if (customers.find((c) => c.identifier === normalized)) {
    /* Generic message — no user enumeration */
    const e = new Error("Registrazione non possibile. Contatta il supporto.");
    e.statusCode = 409;
    throw e;
  }
  const hash = await hashPassword(password);
  const customerId = generateCustomerId();

  await appendRow(SHEET.CUSTOMERS, [
    customerId,
    clean(full_name),
    normalized,
    detectIdentifierType(normalized),
    hash,
    "true",
    new Date().toISOString(),
  ]);

  return { success: true, customerId };
}

/* ─────────────────────────────────────────────────────────────
   LOGIN (CUSTOMER)
───────────────────────────────────────────────────────────── */

/**
 * Authenticate a customer.
 * Returns { success: true, customerId, full_name } or throws.
 * Uses constant-time comparison to prevent timing attacks.
 */
async function login({ identifier, password }) {
  if (!identifier?.trim() || !password) {
    const e = new Error("Credenziali non valide.");
    e.statusCode = 401;
    throw e;
  }

  const normalized = normalizeIdentifier(identifier);
  const customers  = await readCustomers();
  const customer   = customers.find((c) => c.identifier === normalized);

  /* Always run bcrypt even if user not found — prevents timing oracle */
  const hashToCheck = customer?.passwordHash || "$2b$12$invalidhashpadding00000000000000000000000000000000000";
  const match = await verifyPassword(password, customer);

  if (!customer || !match) {
    const e = new Error("Credenziali non valide.");
    e.statusCode = 401;
    throw e;
  }

  if (!customer.active) {
    const e = new Error("Account sospeso. Contatta il supporto.");
    e.statusCode = 403;
    throw e;
  }

  return {
    success:    true,
    customerId: customer.id,
    full_name:  customer.full_name,
  };
}

/* ─────────────────────────────────────────────────────────────
   LOGIN (PARTNER)
   Partners are managed via loyalty-partners.json for MVP simplicity.
───────────────────────────────────────────────────────────── */

/**
 * Authenticate a partner business.
 * Returns { success: true, partnerId, name } or throws.
 */
async function loginPartner({ partnerId, password }) {
  if (!partnerId?.trim() || !password) {
    const e = new Error("Credenziali non valide.");
    e.statusCode = 401;
    throw e;
  }

  /* Partners loaded from JSON file — avoids a Sheets call on every login */
  let partners = [];
  try {
    partners = require("../data/loyalty-partners.json");
  } catch {
    const e = new Error("Servizio temporaneamente non disponibile.");
    e.statusCode = 503;
    throw e;
  }

  const partner = partners.find((p) => p.id === partnerId.trim());
  /* Constant-time compare even for partner passwords */
  const hashToCheck = partner?.passwordHash || "$2b$12$invalidhashpadding00000000000000000000000000000000000";
  const match = await verifyPassword(password, partners);

  if (!partner || !match) {
    const e = new Error("Credenziali non valide.");
    e.statusCode = 401;
    throw e;
  }

  if (partner.active === false) {
    const e = new Error("Account sospeso.");
    e.statusCode = 403;
    throw e;
  }

  return { success: true, partnerId: partner.id, name: partner.name };
}

/* ─────────────────────────────────────────────────────────────
   QR VALIDATION + REDEMPTION
───────────────────────────────────────────────────────────── */

/**
 * Validate a scanned QR token and record a redemption.
 *
 * Security guarantees:
 *   1. HMAC signature verified by qrService.verifyQrToken()
 *   2. Token TTL verified (short-lived — default 5 min)
 *   3. Replay: check token not already in Redemptions sheet
 *   4. Per-day deduplication: same customer+offer+partner = 1/day
 *   5. Offer must exist and be active
 *   6. Customer must be active
 *
 * @param {string} token       - Signed HMAC token from QR
 * @param {string} offerId     - Offer ID partner is applying
 * @param {string} partnerId   - Authenticated partner ID from session
 */
async function validateRedemption({ token, offerId, partnerId } = {}) {
  const { verifyQrToken } = require("./qrService");

  if (!token || !offerId || !partnerId) {
    return { success: false, message: "Dati mancanti." };
  }

  /* 1. Verify HMAC + expiry */
  const verification = verifyQrToken(token);
  if (!verification.valid) {
    const messages = {
      TOKEN_MISSING:           "QR mancante.",
      TOKEN_MALFORMED:         "QR non valido.",
      TOKEN_INVALID_SIGNATURE: "QR non autentico.",
      TOKEN_EXPIRED:           "QR scaduto. Chiedi al cliente di aggiornare il QR.",
    };
    return {
      success: false,
      message: messages[verification.reason] || "QR non valido.",
    };
  }

  const { customerId } = verification;

  /* 2. Load data — parallel for performance */
  const [customers, offers, redemptions] = await Promise.all([
    readCustomers(),
    readOffers(),
    readRedemptions(),
  ]);

  /* 3. Validate customer */
  const customer = customers.find((c) => c.id === customerId);
  if (!customer) {
    return { success: false, message: "Cliente non trovato." };
  }
  if (!customer.active) {
    return { success: false, message: "Account cliente sospeso." };
  }

  /* 4. Replay attack guard — token already used */
  if (redemptions.find((r) => r.usedToken === token)) {
    return {
      success: false,
      message: "QR già utilizzato. Chiedi al cliente di aggiornare il QR.",
    };
  }

  /* 5. Validate offer */
  const offer = offers.find((o) => o.id === offerId);
  if (!offer || !offer.active) {
    return { success: false, message: "Offerta non valida o non attiva." };
  }

  /* 6. Per-day deduplication */
  const today = new Date().toISOString().slice(0, 10);
  const alreadyToday = redemptions.find(
    (r) =>
      r.customerId === customerId &&
      r.offerId    === offerId    &&
      r.partnerId  === partnerId &&
      r.date       === today
  );
  if (alreadyToday) {
    return {
      success: false,
      message: "Questo cliente ha già usato questa offerta oggi.",
    };
  }

  /* 7. Record redemption */
  const redemptionId = `r-${Date.now()}`;
  await appendRow(SHEET.REDEMPTIONS, [
    redemptionId,
    customerId,
    clean(partnerId),
    clean(offerId),
    token,           // store the used token for replay prevention
    today,
    new Date().toISOString(),
  ]);

  return {
    success:       true,
    message:       `✓ Sconto applicato: ${offer.title}`,
    customerName:  customer.full_name,
    offerTitle:    offer.title,
    redemptionId,
  };
}

/* ─────────────────────────────────────────────────────────────
   OFFER MANAGEMENT
───────────────────────────────────────────────────────────── */

async function createOffer({ title, description = "", partnerId = "" }) {
  if (!title?.trim()) {
    const e = new Error("Il titolo dell'offerta è obbligatorio.");
    e.statusCode = 400;
    throw e;
  }

  const offer = {
    id:          `offer-${Date.now()}`,
    title:       clean(title),
    description: clean(description),
    partnerId:   clean(partnerId),
    active:      "true",
    createdAt:   new Date().toISOString(),
  };

  await appendRow(SHEET.OFFERS, [
    offer.id,
    offer.title,
    offer.description,
    offer.partnerId,
    offer.active,
    offer.createdAt,
  ]);

  return { success: true, offer };
}

/* ─────────────────────────────────────────────────────────────
   ADMIN READS
───────────────────────────────────────────────────────────── */

async function getCustomers() {
  return readCustomers();
}

async function getRedemptions() {
  return readRedemptions();
}

async function getOffers() {
  return readOffers();
}

/* ─────────────────────────────────────────────────────────────
   EXPORTS
───────────────────────────────────────────────────────────── */

module.exports = {
  register,
  login,
  loginPartner,
  validateRedemption,
  createOffer,
  getCustomers,
  getRedemptions,
  getOffers,
};
