"use strict";

/**
 * services/loyaltyService.js
 *
 * CHANGES FROM ORIGINAL:
 *   - SHA-256 password hashing → argon2
 *   - All user input sanitized before Sheets writes
 *   - Structured error objects instead of throw strings
 *   - No user enumeration on login (same error for wrong user vs wrong password)
 *   - `getByToken` no longer exported — internal only
 *   - Rate-limit-friendly: login does not leak whether email exists
 *   - QR token is now generated by qrService (HMAC-signed, TTL-bound)
 *     The token stored in Sheets is the customer UID, NOT the signed QR
 *   - Full JSDoc for maintainability
 */
const { appendRow, getSheetValues }              = require("./sheetsService");
const { clean }                                  = require("../utils/sanitizer");
const { generateCustomerId, verifyQrToken }      = require("./qrService");
const { hashPassword, verifyPassword }           = require("../utils/argon2");
const { redisClient: redis }                     = require ("../utils/redis");
const crypto = require("crypto");

const SHEET = {
  CUSTOMERS:   "Customers",
  REDEMPTIONS: "Redemptions",
  OFFERS:      "Offers",
};

/* ─────────────────────────────────────────────────────────────
   SHEET READERS
   Each function reads + maps one sheet tab.
   Reminder: header row is always row[0] — strip it.
───────────────────────────────────────────────────────────── */

async function readCustomers() {
  const rows = await getSheetValues(SHEET.CUSTOMERS);
  return rows.slice(1).map((r) => ({
    id:             r[0],
    full_name:      r[1],
    identifier:     r[2],
    identifierType: r[3],
    passwordHash:   r[4],
    active:         r[5] === "true" || r[5] === "TRUE",
    createdAt:      r[6],
  }));
}

async function readRedemptions() {
  const rows = await getSheetValues(SHEET.REDEMPTIONS);
  return rows.slice(1).map((r) => ({
    id:          r[0],
    customerId:  r[1],
    partnerId:   r[2],
    offerId:     r[3],
    usedToken:   r[4],  // the HMAC token that was consumed (replay guard)
    date:        r[5],
    createdAt:   r[6],
  }));
}

async function readOffers() {
  const rows = await getSheetValues(SHEET.OFFERS);
  return rows.slice(1).map((r) => ({
    id:          r[0],
    title:       r[1],
    description: r[2],
    partnerId:   r[3],
    active:      r[4] === "true" || r[4] === "TRUE",
    createdAt:   r[5],
  }));
}

/* ─────────────────────────────────────────────────────────────
   HELPERS
───────────────────────────────────────────────────────────── */

function normalizeIdentifier(identifier) {
  const trimmed = identifier.trim().toLowerCase();
  return trimmed.includes("@")
    ? trimmed
    : trimmed.replace(/[^\d+]/g, "");
}

function detectIdentifierType(identifier) {
  return identifier.includes("@") ? "email" : "phone";
}

function makeError(message, statusCode = 400) {
  const err = new Error(message);
  err.statusCode = statusCode;
  return err;
}

/* ─────────────────────────────────────────────────────────────
   CUSTOMER — REGISTER
───────────────────────────────────────────────────────────── */

/**
 * Register a new customer.
 * Returns { success: true, customerId } or throws with a safe message.
 */
async function register({ full_name, identifier, password }) {
  if (!full_name?.trim() || !identifier?.trim() || !password) {
    throw makeError("Tutti i campi sono obbligatori.", 400);
  }

  if (password.length < 8) {
    throw makeError("La password deve avere almeno 8 caratteri.", 400);
  }

  const normalized = normalizeIdentifier(identifier);
  const customers  = await readCustomers();

  if (customers.find((c) => c.identifier === normalized)) {
    /* Generic message — no user enumeration */
    throw makeError("Registrazione non possibile. Contatta il supporto.", 409);
  }
  const hash = await hashPassword(password);
  const customerId = generateCustomerId();

  await appendRow(SHEET.CUSTOMERS, [
    customerId,
    clean(full_name),
    normalized,
    detectIdentifierType(normalized),
    hash,
    "true",
    new Date().toISOString(),
  ]);

  return { success: true, customerId, full_name: clean(full_name) };
}

/* ─────────────────────────────────────────────────────────────
   CUSTOMER - LOGIN
───────────────────────────────────────────────────────────── */

/**
 * Authenticate a customer.
 * Returns { success: true, customerId, full_name } or throws.
 * Uses constant-time comparison to prevent timing attacks.
 */
async function login({ identifier, password }) {
  if (!identifier?.trim() || !password) {
    throw makeError("Credenziali non valide.", 401);
  }

  const normalized = normalizeIdentifier(identifier);
  const customers  = await readCustomers();
  const customer   = customers.find((c) => c.identifier === normalized);

  const match = await verifyPassword(password, customer);

  if (!customer || !match) throw makeError("Credenziali non valide.", 401);


  if (!customer.active) throw makeError("Account sospeso. Contatta il supporto.", 403);

  return {
    success:    true,
    customerId: customer.id,
    full_name:  customer.full_name,
  };
}

/* ─────────────────────────────────────────────────────────────
   PARTNER - LOGIN
   Partners are managed via loyalty-partners.json for MVP simplicity.
───────────────────────────────────────────────────────────── */

/**
 * Authenticate a partner business.
 * Returns { success: true, partnerId, name } or throws.
 */

async function getPartnerById(partnerId) {
  const raw = await redis.get(`mm:partner:${partnerId}`);
  if (!raw) return null;
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}
 
async function getAllPartners() {
  const ids = await redis.sMembers("mm:partners:index");
  if (!ids.length) return [];
 
  const pipeline = redis.multi();
  ids.forEach((id) => pipeline.get(`mm:partner:${id}`));
  const results = await pipeline.exec();
 
  return results
    .map((r) => (r ? (typeof r === "string" ? JSON.parse(r) : r) : null))
    .filter(Boolean);
}

async function loginPartner({ partnerId, password }) {
  if (!partnerId?.trim() || !password) throw makeError("Credenziali non valide.", 401);

  /* Partners loaded from JSON file — avoids a Sheets call on every login */
  let partner = null;
  try {
    partner = await getPartnerById(partnerId.trim());
  } catch(e) {
    console.log(e);
     throw makeError("Servizio temporaneamente non disponibile.", 503);
  }

  const match =  await verifyPassword(password, partner);

  if (!partner || !match) throw makeError("Credenziali non valide.", 401);

  if (!partner.active) throw makeError("Account sospeso.", 403);

  return { 
    success: true, 
    partnerId: partner.id, 
    name: partner.name, 
    mustChangePassword: partner.mustChangePassword === true 
  };
}

/* ─────────────────────────────────────────────────────────────
   PARTNER — SET PASSWORD (first login flow)
───────────────────────────────────────────────────────────── */
 
async function setPartnerPassword({ partnerId, newPassword }) {
  if (!newPassword || newPassword.length < 8) {
    throw makeError("La nuova password deve avere almeno 8 caratteri.", 400);
  }
 
  const partner = await getPartnerById(partnerId);
  if (!partner) throw makeError("Partner non trovato.", 404);
 
  const hash    = await hashPassword(newPassword);
  const updated = { ...partner, passwordHash: hash, mustChangePassword: false };
 
  await redis.set(`mm:partner:${partnerId}`, JSON.stringify(updated));
  return { success: true };
}

/* ─────────────────────────────────────────────────────────────
   PARTNER — CREATE (called by admin)
───────────────────────────────────────────────────────────── */
 
async function createPartner({ id, name, category, address, tempPassword }) {
  if (!id?.trim() || !name?.trim() || !tempPassword) throw makeError("ID, nome e password temporanea sono obbligatori.", 400);
 
  const cleanId = clean(id).toLowerCase().replace(/\s+/g, "-");
 
  const existing = await getPartnerById(cleanId);
  if (existing) throw makeError("Un partner con questo ID esiste già.", 409);
 
  if (tempPassword.length < 8) throw makeError("La password temporanea deve avere almeno 8 caratteri.", 400);
 
  const hash    = await hashPassword(tempPassword);
  const partner = {
    id:                cleanId,
    name:              clean(name),
    category:          clean(category || "Generico"),
    address:           clean(address || ""),
    passwordHash:      hash,
    mustChangePassword: true,
    active:            true,
    createdAt:         new Date().toISOString(),
  };
 
  await redis.set(`mm:partner:${cleanId}`, JSON.stringify(partner));
  await redis.sAdd("mm:partners:index", cleanId);
 
  return { success: true, partnerId: cleanId };
}

/* ─────────────────────────────────────────────────────────────
   PARTNER — UPDATE ACTIVE STATUS (admin)
───────────────────────────────────────────────────────────── */
 
async function setPartnerActive(partnerId, active) {
  const partner = await getPartnerById(partnerId);
  if (!partner) throw makeError("Partner non trovato.", 404);
  const updated = { ...partner, active };
  await redis.set(`mm:partner:${partnerId}`, JSON.stringify(updated));
  return { success: true };
}

/* ─────────────────────────────────────────────────────────────
   OFFERS
───────────────────────────────────────────────────────────── */

async function getActiveOffers() {
  const offers = await readOffers();
  return offers.filter((o) => o.active);
}
 
async function getPartnerOffers(partnerId) {
  const offers = await readOffers();
  return offers.filter(
    (o) => o.active && (!o.partnerId || o.partnerId === partnerId)
  );
}

async function createOffer({ title, description, partnerId }) {
  if (!title?.trim()) {
    throw makeError("Il titolo dell'offerta è obbligatorio.", 400);
  }
 
  const id  = `offer-${Date.now()}-${crypto.randomBytes(4).toString("hex")}`;
  const now = new Date().toISOString();
 
  await appendRow(SHEET.OFFERS, [
    id,
    clean(title),
    clean(description || ""),
    clean(partnerId   || ""),
    "true",
    now,
  ]);
 
  return {
    success: true,
    offer:   { id, title: clean(title), description: clean(description || ""), partnerId: clean(partnerId || ""), active: true, createdAt: now },
  };
}

/* ─────────────────────────────────────────────────────────────
   QR VALIDATION + REDEMPTION
───────────────────────────────────────────────────────────── */

/**
 * Validate a scanned QR token and record a redemption.
 *
 * Security guarantees:
 *   1. HMAC signature verified by qrService.verifyQrToken()
 *   2. Token TTL verified (short-lived — default 5 min)
 *   3. Replay: check token not already in Redemptions sheet
 *   4. Per-day deduplication: same customer+offer+partner = 1/day
 *   5. Offer must exist and be active
 *   6. Customer must be active
 *
 * @param {string} token       - Signed HMAC token from QR
 * @param {string} offerId     - Offer ID partner is applying
 * @param {string} partnerId   - Authenticated partner ID from session
 */
async function prevalidateQr({ token, partnerId } = {}) {

  if (!token || !partnerId) return { success: false, message: "Dati mancanti." };

    /* 1. Signature + expiry */
  const check = verifyQrToken(token);

  /* 1. Verify HMAC + expiry */
  if (!check.valid) {
    const messages = {
      TOKEN_MISSING:           "QR mancante.",
      TOKEN_MALFORMED:         "QR non valido.",
      TOKEN_INVALID_SIGNATURE: "QR non autentico — rifiuta la transazione.",
      TOKEN_EXPIRED:           "QR scaduto. Chiedi al cliente di aggiornare il QR.",
    };
    return { success: false, code: check.reason, message: messages[check.reason] || "QR non valido.", expiresAt: null };
  }

  const { customerId, exp } = check;

  /* 2. Check QR replay lock (already used?) */
  const tokenHash  = crypto.createHash("sha256").update(token).digest("hex");
  const replayUsed = await redis.exists(`mm:usedqr:${tokenHash}`);
  if (replayUsed) {
    return { success: false, code: "TOKEN_ALREADY_USED", message: "QR già utilizzato. Chiedi al cliente di aggiornare il QR.", expiresAt: null };
  }

  /* 3. Load customer */
  const customers = await readCustomers();
  const customer  = customers.find((c) => c.id === customerId);
  if (!customer)       return { success: false, code: "CUSTOMER_NOT_FOUND", message: "Cliente non trovato.", expiresAt: null };
  if (!customer.active) return { success: false, code: "CUSTOMER_SUSPENDED", message: "Account cliente sospeso.", expiresAt: null };

  /* 4. Load offers + check per-offer eligibility */
  const offers = await getPartnerOffers(partnerId);
 
  const eligibleOffers = await Promise.all(
    offers.map(async (offer) => {
      const lockKey = `mm:redeemed:${partnerId}:${offer.id}:${customerId}`;
      const used    = await redis.exists(lockKey);
      return {
        id:          offer.id,
        title:       offer.title,
        description: offer.description,
        eligible:    !used,
        reason:      used ? "Già utilizzata" : null,
      };
    })
  );


    return {
    success:        true,
    customerId,
    customerName:   customer.full_name,
    expiresAt:      exp,
    eligibleOffers,
  };
};

/* ─────────────────────────────────────────────────────────────
   REDEMPTION — FULL ATOMIC FLOW
   Layer 1: QR signature + expiry      (qrService.verifyQrToken)
   Layer 2: QR replay lock             (Redis SET NX)
   Layer 3: Permanent offer lock       (Redis SET NX, no TTL)
   Layer 4: Idempotency key            (Redis SET NX EX 300)
   Layer 5: Sheets audit write         (fire-and-forget)
───────────────────────────────────────────────────────────── */
async function redeemOffer({ token, offerId, partnerId, idempotencyKey }) {
  /* ─────────────────────────────────────────────────────────────
     0. IDEMPOTENCY
     Same request repeated = same response returned
  ───────────────────────────────────────────────────────────── */
  if (idempotencyKey) {
    const idemKey   = `mm:idempotency:${idempotencyKey}`;
    const cachedRaw = await redis.get(idemKey);

    if (cachedRaw) {
      return typeof cachedRaw === "string"
        ? JSON.parse(cachedRaw)
        : cachedRaw;
    }
  }

  /* ─────────────────────────────────────────────────────────────
     1. VERIFY QR TOKEN
  ───────────────────────────────────────────────────────────── */
  const check = verifyQrToken(token);

  if (!check.valid) {
    const messages = {
      TOKEN_MISSING:           "QR mancante.",
      TOKEN_MALFORMED:         "QR non valido.",
      TOKEN_INVALID_SIGNATURE: "QR non autentico.",
      TOKEN_EXPIRED:           "QR scaduto. Chiedi al cliente di aggiornare il QR.",
    };

    return {
      success: false,
      code: check.reason,
      message: messages[check.reason] || "QR non valido.",
    };
  }

  /* ─────────────────────────────────────────────────────────────
     2. NORMALIZE IDS
     Prevent Redis key mismatches due to type inconsistencies
  ───────────────────────────────────────────────────────────── */
  const normalizedCustomerId = String(check.customerId).trim();
  const normalizedOfferId    = String(offerId).trim();
  const normalizedPartnerId  = String(partnerId).trim();

  /* ─────────────────────────────────────────────────────────────
     3. TEMPORARY QR REPLAY PROTECTION
     Prevent same QR reuse during QR lifetime
  ───────────────────────────────────────────────────────────── */
  const tokenHash = crypto
    .createHash("sha256")
    .update(token)
    .digest("hex");

  const replayKey = `mm:usedqr:${tokenHash}`;

  const ttlSeconds = Math.ceil(
    parseInt(process.env.LOYALTY_QR_TTL_MS || "300000", 10) / 1000
  );

  const replayLock = await redis.set(
    replayKey,
    "1",
    {
      nx: true,
      ex: ttlSeconds,
    }
  );

  if (replayLock === null) {
    return {
      success: false,
      code: "TOKEN_ALREADY_USED",
      message: "QR già utilizzato. Chiedi al cliente di aggiornare il QR.",
    };
  }

  /* ─────────────────────────────────────────────────────────────
     4. VALIDATE CUSTOMER
  ───────────────────────────────────────────────────────────── */
  const customers = await readCustomers();

  const customer = customers.find(
    (c) => String(c.id).trim() === normalizedCustomerId
  );

  if (!customer) {
    await redis.del(replayKey);

    return {
      success: false,
      code: "CUSTOMER_NOT_FOUND",
      message: "Cliente non trovato.",
    };
  }

  if (!customer.active) {
    await redis.del(replayKey);

    return {
      success: false,
      code: "CUSTOMER_SUSPENDED",
      message: "Account cliente sospeso.",
    };
  }

  /* ─────────────────────────────────────────────────────────────
     5. VALIDATE OFFER
  ───────────────────────────────────────────────────────────── */
  const offers = await readOffers();

  const offer = offers.find(
    (o) => String(o.id).trim() === normalizedOfferId
  );

  if (!offer || !offer.active) {
    await redis.del(replayKey);

    return {
      success: false,
      code: "OFFER_INVALID",
      message: "Offerta non valida o non attiva.",
    };
  }

  /* ─────────────────────────────────────────────────────────────
     6. PERMANENT BUSINESS REDEMPTION LOCK
     Prevent same customer redeeming same offer
     at same partner forever
  ───────────────────────────────────────────────────────────── */
  const redemptionKey =
    `mm:redeemed:${normalizedPartnerId}:${normalizedOfferId}:${normalizedCustomerId}`;

  const redemptionData = JSON.stringify({
    customerId: normalizedCustomerId,
    partnerId:  normalizedPartnerId,
    offerId:    normalizedOfferId,
    redeemedAt: Date.now(),
  });

  console.log("[redeemOffer] redemptionKey =", redemptionKey);

  const redemptionLock = await redis.set(
    redemptionKey,
    redemptionData,
    { nx: true }
  );

  if (redemptionLock === null) {
    /* Redemption failed → release temporary QR replay lock */
    await redis.del(replayKey);

    return {
      success: false,
      code: "OFFER_ALREADY_REDEEMED",
      message: "Questo cliente ha già utilizzato questa offerta.",
    };
  }

  /* ─────────────────────────────────────────────────────────────
     7. BUILD REDEMPTION RECORD
  ───────────────────────────────────────────────────────────── */
  const redemptionId =
    `r-${Date.now()}-${crypto.randomBytes(4).toString("hex")}`;

  const now    = new Date();
  const nowIso = now.toISOString();

  /* ─────────────────────────────────────────────────────────────
     8. PERSIST TO SHEETS (AUDIT TRAIL)
  ───────────────────────────────────────────────────────────── */
  appendRow(SHEET.REDEMPTIONS, [
    redemptionId,
    normalizedCustomerId,
    normalizedPartnerId,
    normalizedOfferId,
    tokenHash,
    now.toISOString().slice(0, 10),
    nowIso,
  ]).catch((err) => {
    console.error(
      "[loyaltyService/redeemOffer] Sheets write failed:",
      err.message
    );
  });

  /* ─────────────────────────────────────────────────────────────
     9. SUCCESS RESPONSE
  ───────────────────────────────────────────────────────────── */
  const result = {
    success: true,
    redemptionId,
    customerName: customer.full_name,
    offerTitle: offer.title,
    message: `${offer.title} applicato per ${customer.full_name}`,
    redeemedAt: nowIso,
  };

  /* ─────────────────────────────────────────────────────────────
     10. CACHE IDEMPOTENT RESPONSE
  ───────────────────────────────────────────────────────────── */
  if (idempotencyKey) {
    await redis.set(
      `mm:idempotency:${idempotencyKey}`,
      JSON.stringify(result),
      { ex: 300 }
    );
  }

  return result;
}

  /* ─────────────────────────────────────────────────────────────
   ADMIN READS
───────────────────────────────────────────────────────────── */

async function getCustomers() {
  return readCustomers();
}

async function getRedemptions() {
  return readRedemptions();
}

async function getOffers() {
  return readOffers();
}

/* ─────────────────────────────────────────────────────────────
   EXPORTS
───────────────────────────────────────────────────────────── */

module.exports = {
  /* Customer */
  register,
  login,
  /* Partner */
  loginPartner,
  setPartnerPassword,
  createPartner,
  setPartnerActive,
  getAllPartners,
  getPartnerById,
  /* Offers */
  getActiveOffers,
  getPartnerOffers,
  createOffer,
  /* QR */
  prevalidateQr,
  redeemOffer,
  /* Admin reads */
  getCustomers,
  getRedemptions,
  getOffers,
};
