"use strict";

/**
 * services/loyaltyService.js
 *
 * CHANGES FROM ORIGINAL:
 *   - SHA-256 password hashing → argon2
 *   - All user input sanitized before Sheets writes
 *   - Structured error objects instead of throw strings
 *   - No user enumeration on login (same error for wrong user vs wrong password)
 *   - `getByToken` no longer exported — internal only
 *   - Rate-limit-friendly: login does not leak whether email exists
 *   - QR token is now generated by qrService (HMAC-signed, TTL-bound)
 *     The token stored in Sheets is the customer UID, NOT the signed QR
 *   - Full JSDoc for maintainability
 */
const { appendRow, getSheetValues }              = require("./sheetsService");
const { clean }                                  = require("../utils/sanitizer");
const { generateCustomerId, verifyQrToken }      = require("./qrService");
const { hashPassword, verifyPassword }           = require("../utils/argon2");
const { redisClient: redis }                     = require ("../utils/redis");
const crypto = require("crypto");
const db = require("../db"); // your pg wrapper

const SHEET = {
  CUSTOMERS:   "Customers",
  REDEMPTIONS: "Redemptions",
  OFFERS:      "Offers",
};

/* ─────────────────────────────────────────────────────────────
   SHEET READERS
   Each function reads + maps one sheet tab.
   Reminder: header row is always row[0] — strip it.
───────────────────────────────────────────────────────────── */

async function readCustomers() {
  const rows = await getSheetValues(SHEET.CUSTOMERS);
  return rows.slice(1).map((r) => ({
    id:             r[0],
    full_name:      r[1],
    identifier:     r[2],
    identifierType: r[3],
    passwordHash:   r[4],
    active:         r[5] === "true" || r[5] === "TRUE",
    createdAt:      r[6],
  }));
}

async function readRedemptions() {
  const rows = await getSheetValues(SHEET.REDEMPTIONS);
  return rows.slice(1).map((r) => ({
    id:          r[0],
    customerId:  r[1],
    partnerId:   r[2],
    offerId:     r[3],
    usedToken:   r[4],  // the HMAC token that was consumed (replay guard)
    date:        r[5],
    createdAt:   r[6],
  }));
}

async function readOffers() {
  const rows = await getSheetValues(SHEET.OFFERS);
  return rows.slice(1).map((r) => ({
    id:          r[0],
    title:       r[1],
    description: r[2],
    partnerId:   r[3],
    active:      r[4] === "true" || r[4] === "TRUE",
    createdAt:   r[5],
  }));
}

/* ─────────────────────────────────────────────────────────────
   HELPERS
───────────────────────────────────────────────────────────── */

function normalizeIdentifier(identifier) {
  const trimmed = identifier.trim().toLowerCase();
  return trimmed.includes("@")
    ? trimmed
    : trimmed.replace(/[^\d+]/g, "");
}

function detectIdentifierType(identifier) {
  return identifier.includes("@") ? "email" : "phone";
}

function makeError(message, statusCode = 400) {
  const err = new Error(message);
  err.statusCode = statusCode;
  return err;
}

/* ─────────────────────────────────────────────────────────────
   CUSTOMER — REGISTER
───────────────────────────────────────────────────────────── */

/**
 * Register a new customer.
 * Returns { success: true, customerId } or throws with a safe message.
 */

async function register({ full_name, identifier, password }) {
  if (!full_name?.trim() || !identifier?.trim() || !password) {
    throw makeError("Tutti i campi sono obbligatori.", 400);
  }

  if (password.length < 8) {
    throw makeError("La password deve avere almeno 8 caratteri.", 400);
  }

  const normalized = normalizeIdentifier(identifier);
  const hash = await hashPassword(password);
  const customerId = generateCustomerId();
  const nowIso = new Date().toISOString();

  const identifierType = detectIdentifierType(normalized);

  /* ─────────────────────────────────────────────
     1. INSERT (DB IS SOURCE OF TRUTH)
     Handles race conditions via UNIQUE constraint
  ───────────────────────────────────────────── */
  try {
    await db.query(
      `
      INSERT INTO customers (
        id,
        full_name,
        identifier,
        identifier_type,
        password_hash,
        active,
        created_at
      )
      VALUES ($1, $2, $3, $4, $5, $6, NOW())
      `,
      [
        customerId,
        clean(full_name),
        normalized,
        identifierType,
        hash,
        true,
      ]
    );
  } catch (err) {
    /* Unique violation = already exists */
    if (err.code === "23505") {
      throw makeError(
        "Registrazione non possibile. Contatta il supporto.",
        409
      );
    }
    throw err;
  }

  /* ─────────────────────────────────────────────
     2. OPTIONAL: SHEETS SYNC (LEGACY)
     Non-blocking, can be removed later
  ───────────────────────────────────────────── */
  appendRow(SHEET.CUSTOMERS, [
    customerId,
    clean(full_name),
    normalized,
    identifierType,
    hash,
    "true",
    nowIso,
  ]).catch((err) => {
    console.error("[register] Sheets sync failed:", err.message);
  });

  /* ─────────────────────────────────────────────
     3. RESPONSE
  ───────────────────────────────────────────── */
  return {
    success: true,
    customerId,
    full_name: clean(full_name),
  };
}

/* ─────────────────────────────────────────────────────────────
   CUSTOMER - LOGIN
───────────────────────────────────────────────────────────── */

/**
 * Authenticate a customer.
 * Returns { success: true, customerId, full_name } or throws.
 * Uses constant-time comparison to prevent timing attacks.
 */
async function login({ identifier, password }) {
  if (!identifier?.trim() || !password) {
    throw makeError("Credenziali non valide.", 401);
  }

  const normalized = normalizeIdentifier(identifier);
  const customers  = await readCustomers();
  const customer   = customers.find((c) => c.identifier === normalized);

  const match = await verifyPassword(password, customer);

  if (!customer || !match) throw makeError("Credenziali non valide.", 401);


  if (!customer.active) throw makeError("Account sospeso. Contatta il supporto.", 403);

  return {
    success:    true,
    customerId: customer.id,
    full_name:  customer.full_name,
  };
}

/* ─────────────────────────────────────────────────────────────
   PARTNER - LOGIN
   Partners are managed via loyalty-partners.json for MVP simplicity.
───────────────────────────────────────────────────────────── */

/**
 * Authenticate a partner business.
 * Returns { success: true, partnerId, name } or throws.
 */

async function getPartnerById(partnerId) {
  const raw = await redis.get(`mm:partner:${partnerId}`);
  if (!raw) return null;
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}
 
async function getAllPartners() {
  const ids = await redis.sMembers("mm:partners:index");
  if (!ids.length) return [];
 
  const pipeline = redis.multi();
  ids.forEach((id) => pipeline.get(`mm:partner:${id}`));
  const results = await pipeline.exec();
 
  return results
    .map((r) => (r ? (typeof r === "string" ? JSON.parse(r) : r) : null))
    .filter(Boolean);
}

async function loginPartner({ partnerId, password }) {
  if (!partnerId?.trim() || !password) throw makeError("Credenziali non valide.", 401);

  /* Partners loaded from JSON file — avoids a Sheets call on every login */
  let partner = null;
  try {
    partner = await getPartnerById(partnerId.trim());
  } catch(e) {
    console.log(e);
     throw makeError("Servizio temporaneamente non disponibile.", 503);
  }

  const match =  await verifyPassword(password, partner);

  if (!partner || !match) throw makeError("Credenziali non valide.", 401);

  if (!partner.active) throw makeError("Account sospeso.", 403);

  return { 
    success: true, 
    partnerId: partner.id, 
    name: partner.name, 
    mustChangePassword: partner.mustChangePassword === true 
  };
}

/* ─────────────────────────────────────────────────────────────
   PARTNER — SET PASSWORD (first login flow)
───────────────────────────────────────────────────────────── */
 
async function setPartnerPassword({ partnerId, newPassword }) {
  if (!newPassword || newPassword.length < 8) {
    throw makeError("La nuova password deve avere almeno 8 caratteri.", 400);
  }
 
  const partner = await getPartnerById(partnerId);
  if (!partner) throw makeError("Partner non trovato.", 404);
 
  const hash    = await hashPassword(newPassword);
  const updated = { ...partner, passwordHash: hash, mustChangePassword: false };
 
  await redis.set(`mm:partner:${partnerId}`, JSON.stringify(updated));
  return { success: true };
}


async function createPartner({ id, name, category, address, tempPassword }) {
  if (!id?.trim() || !name?.trim() || !tempPassword) {
    throw makeError(
      "ID, nome e password temporanea sono obbligatori.",
      400
    );
  }

  const cleanId = clean(id).toLowerCase().replace(/\s+/g, "-");

  /* ─────────────────────────────────────────────
     1. CHECK EXISTING PARTNER (DB IS SOURCE OF TRUTH)
  ───────────────────────────────────────────── */
  const existing = await db.query(
    `SELECT id FROM partners WHERE id = $1`,
    [cleanId]
  );

  if (existing.rowCount > 0) {
    throw makeError("Un partner con questo ID esiste già.", 409);
  }

  /* ─────────────────────────────────────────────
     2. VALIDATE PASSWORD
  ───────────────────────────────────────────── */
  if (tempPassword.length < 8) {
    throw makeError(
      "La password temporanea deve avere almeno 8 caratteri.",
      400
    );
  }

  const hash = await hashPassword(tempPassword);

  const nowIso = new Date().toISOString();

  /* ─────────────────────────────────────────────
     3. INSERT INTO POSTGRES (SOURCE OF TRUTH)
  ───────────────────────────────────────────── */
  await db.query(
    `
    INSERT INTO partners (
      id,
      name,
      category,
      address,
      password_hash,
      must_change_password,
      active,
      created_at
    )
    VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
    `,
    [
      cleanId,
      clean(name),
      clean(category || "Generico"),
      clean(address || ""),
      hash,
      true,
      true,
    ]
  );

  /* ─────────────────────────────────────────────
     4. OPTIONAL REDIS CACHE (NOT SOURCE OF TRUTH)
     Keep only for fast access if needed
  ───────────────────────────────────────────── */
  const partner = {
    id: cleanId,
    name: clean(name),
    category: clean(category || "Generico"),
    address: clean(address || ""),
    passwordHash: hash,
    mustChangePassword: true,
    active: true,
    createdAt: nowIso,
  };

  await redis
    .set(`mm:partner:${cleanId}`, JSON.stringify(partner))
    .catch(() => {});

  await redis.sAdd("mm:partners:index", cleanId).catch(() => {});

  /* ─────────────────────────────────────────────
     5. RESPONSE
  ───────────────────────────────────────────── */
  return {
    success: true,
    partnerId: cleanId,
  };
}

/* ─────────────────────────────────────────────────────────────
   PARTNER — UPDATE ACTIVE STATUS (admin)
───────────────────────────────────────────────────────────── */
 
async function setPartnerActive(partnerId, active) {
  const partner = await getPartnerById(partnerId);
  if (!partner) throw makeError("Partner non trovato.", 404);
  const updated = { ...partner, active };
  await redis.set(`mm:partner:${partnerId}`, JSON.stringify(updated));
  return { success: true };
}

/* ─────────────────────────────────────────────────────────────
   OFFERS
───────────────────────────────────────────────────────────── */

async function getActiveOffers() {
  const offers = await readOffers();
  return offers.filter((o) => o.active);
}
 
async function getPartnerOffers(partnerId) {
  const offers = await readOffers();
  return offers.filter(
    (o) => o.active && (!o.partnerId || o.partnerId === partnerId)
  );
}

async function createOffer({ title, description, partnerId }) {
  if (!title?.trim()) {
    throw makeError("Il titolo dell'offerta è obbligatorio.", 400);
  }
 
  const cleanTitle = clean(title);
  const cleanDesc = clean(description || "");
  const cleanPartnerId = clean(partnerId || "");

  const id = `offer-${Date.now()}-${crypto.randomBytes(4).toString("hex")}`;
  const nowIso = new Date().toISOString();
 
    /* ─────────────────────────────────────────────
     1. WRITE TO POSTGRES (SOURCE OF TRUTH)
  ───────────────────────────────────────────── */
  await db.query(
    `
    INSERT INTO offers (
      id,
      title,
      description,
      partner_id,
      active,
      created_at
    )
    VALUES ($1, $2, $3, $4, $5, NOW())
    `,
    [
      id,
      cleanTitle,
      cleanDesc,
      cleanPartnerId,
      true,
    ]
  );
  /* ─────────────────────────────────────────────
     2. WRITE TO GOOGLE SHEETS (LEGACY SYNC)
     Do NOT block main flow if it fails
  ───────────────────────────────────────────── */
  await appendRow(SHEET.OFFERS, [
    id,
    clean(title),
    clean(description || ""),
    clean(partnerId   || ""),
    "true",
    nowIso,
  ]);
 
  return {
    success: true,
    offer:   { id, title: clean(title), description: clean(description || ""), partnerId: clean(partnerId || ""), active: true, createdAt: nowIso },
  };
}

/* ─────────────────────────────────────────────────────────────
   QR VALIDATION + REDEMPTION
───────────────────────────────────────────────────────────── */

/**
 * Validate a scanned QR token and record a redemption.
 *
 * Security guarantees:
 *   1. HMAC signature verified by qrService.verifyQrToken()
 *   2. Token TTL verified (short-lived — default 5 min)
 *   3. Replay: check token not already in Redemptions sheet
 *   4. Per-day deduplication: same customer+offer+partner = 1/day
 *   5. Offer must exist and be active
 *   6. Customer must be active
 *
 * @param {string} token       - Signed HMAC token from QR
 * @param {string} offerId     - Offer ID partner is applying
 * @param {string} partnerId   - Authenticated partner ID from session
 */

async function prevalidateQr({ token, partnerId } = {}) {
  if (!token || !partnerId) {
    return { success: false, message: "Dati mancanti." };
  }

  /* 1. VERIFY QR */
  const check = verifyQrToken(token);

  if (!check.valid) {
    const messages = {
      TOKEN_MISSING: "QR mancante.",
      TOKEN_MALFORMED: "QR non valido.",
      TOKEN_INVALID_SIGNATURE: "QR non autentico — rifiuta la transazione.",
      TOKEN_EXPIRED: "QR scaduto. Chiedi al cliente di aggiornare il QR.",
    };

    return {
      success: false,
      code: check.reason,
      message: messages[check.reason] || "QR non valido.",
      expiresAt: null,
    };
  }

  const { customerId, exp } = check;

  /* 2. PARALLEL LOAD (customer + offers) */
  const [customerRes, offers] = await Promise.all([
    db.query(
      `SELECT id, full_name, active FROM customers WHERE id = $1`,
      [customerId]
    ),
    getPartnerOffers(partnerId),
  ]);

  const customer = customerRes.rows[0];

  if (!customer) {
    return {
      success: false,
      code: "CUSTOMER_NOT_FOUND",
      message: "Cliente non trovato.",
      expiresAt: null,
    };
  }

  if (!customer.active) {
    return {
      success: false,
      code: "CUSTOMER_SUSPENDED",
      message: "Account cliente sospeso.",
      expiresAt: null,
    };
  }

  /* 3. BULK FETCH ALL REDEMPTIONS (IMPORTANT OPTIMIZATION) */
  const redemptionsRes = await db.query(
    `
    SELECT offer_id
    FROM redemptions
    WHERE customer_id = $1
      AND partner_id = $2
    `,
    [customerId, partnerId]
  );

  const usedOffers = new Set(redemptionsRes.rows.map(r => r.offer_id));

  /* 4. BUILD RESPONSE (O(N) ONLY) */
  const eligibleOffers = offers.map((offer) => {
    const used = usedOffers.has(offer.id);

    return {
      id: offer.id,
      title: offer.title,
      description: offer.description,
      eligible: !used,
      reason: used ? "Già utilizzata" : null,
    };
  });

  return {
    success: true,
    customerId,
    customerName: customer.full_name,
    expiresAt: exp,
    eligibleOffers,
  };
}

/* ─────────────────────────────────────────────────────────────
   REDEMPTION — FULL ATOMIC FLOW
   Layer 1: QR signature + expiry      (qrService.verifyQrToken)
   Layer 2: QR replay lock             (Redis SET NX)
   Layer 3: Permanent offer lock       (Redis SET NX, no TTL)
   Layer 4: Idempotency key            (Redis SET NX EX 300)
   Layer 5: Sheets audit write         (fire-and-forget)
───────────────────────────────────────────────────────────── */
async function redeemOffer({ token, offerId, partnerId } = {}) {
  /* 1. VERIFY QR */
  const check = verifyQrToken(token);

  if (!check.valid) {
    const messages = {
      TOKEN_MISSING: "QR mancante.",
      TOKEN_MALFORMED: "QR non valido.",
      TOKEN_INVALID_SIGNATURE: "QR non autentico.",
      TOKEN_EXPIRED: "QR scaduto. Chiedi al cliente di aggiornare il QR.",
    };

    return {
      success: false,
      code: check.reason,
      message: messages[check.reason] || "QR non valido.",
    };
  }

  const customerId = String(check.customerId).trim();

  /* 2. SHORT REDIS LOCK (ONLY FOR DOUBLE SCAN PROTECTION) */
  const tokenHash = crypto.createHash("sha256").update(token).digest("hex");
  const lockKey = `mm:scanlock:${tokenHash}:${offerId}`;

  const locked = await redis.set(lockKey, "1", {
    nx: true,
    ex: 5,
  });

  if (!locked) {
    return {
      success: false,
      code: "SCAN_TOO_FAST",
      message: "Scansione già in corso. Riprova.",
    };
  }

  try {
    /* 3. PARALLEL LOAD (customer + offer) */
    const [customerRes, offerRes] = await Promise.all([
      db.query(
        `SELECT id, full_name, active FROM customers WHERE id = $1`,
        [customerId]
      ),
      db.query(
        `SELECT id, title, active 
         FROM offers 
         WHERE id = $1 AND (partner_id = $2 OR partner_id = $3)`,
        [offerId, partnerId, "Globale"]
      ),
    ]);

    const customer = customerRes.rows[0];
    const offer = offerRes.rows[0];

    if (!customer) {
      return { success: false, code: "CUSTOMER_NOT_FOUND", message: "Cliente non trovato." };
    }

    if (!customer.active) {
      return { success: false, code: "CUSTOMER_SUSPENDED", message: "Account cliente sospeso." };
    }

    if (!offer || !offer.active) {
      return { success: false, code: "OFFER_INVALID", message: "Offerta non valida o non attiva." };
    }

    /* 4. INSERT (DB GUARANTEES UNIQUENESS) */
    const redemptionId =
      `r-${Date.now()}-${crypto.randomBytes(4).toString("hex")}`;

    try {
      await db.query(
        `
        INSERT INTO redemptions (
          id,
          customer_id,
          partner_id,
          offer_id,
          used_token,
          redeemed_at
        )
        VALUES ($1, $2, $3, $4, $5, NOW())
        `,
        [redemptionId, customerId, partnerId, offerId, token]
      );
    } catch (err) {
      if (err.code === "23505") {
        return {
          success: false,
          code: "OFFER_ALREADY_REDEEMED",
          message: "Questo cliente ha già utilizzato questa offerta.",
        };
      }
      throw err;
    }

    return {
      success: true,
      redemptionId,
      customerName: customer.full_name,
      offerTitle: offer.title,
      redeemedAt: new Date().toISOString(),
    };

  } finally {
    await redis.del(lockKey).catch(() => {});
  }
}

  /* ─────────────────────────────────────────────────────────────
   ADMIN READS
───────────────────────────────────────────────────────────── */

async function getCustomers() {
  return readCustomers();
}

async function getRedemptions() {
  return readRedemptions();
}

async function getOffers() {
  return readOffers();
}

/* ─────────────────────────────────────────────────────────────
   EXPORTS
───────────────────────────────────────────────────────────── */

module.exports = {
  /* Customer */
  register,
  login,
  /* Partner */
  loginPartner,
  setPartnerPassword,
  createPartner,
  setPartnerActive,
  getAllPartners,
  getPartnerById,
  /* Offers */
  getActiveOffers,
  getPartnerOffers,
  createOffer,
  /* QR */
  prevalidateQr,
  redeemOffer,
  /* Admin reads */
  getCustomers,
  getRedemptions,
  getOffers,
};
